langueage: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t naitao/react-test -f ./client/Dockerfile.dev .

script:
  - docker run -e CI=true naitao/react-test npm run test -- --coverage

after_success:
  - docker build -t naitao/multi-client ./client
  - docker build -t naitao/multi-nginx ./nginx
  - docker build -t naitao/multi-server ./server
  - docker build -t naitao/multi-workder ./worker
# Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
# Take those images and push them to docker hub
  - docker push naitao/multi-client
  - docker push naitao/multi-nginx
  - docker push naitao/multi-server
  - docker push naitao/multi-workder
